services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: pintrest_mock

  redis:
    image: redis
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - redis
    command: pnpm dev
    ports:
      - "8000:8000"
    env_file:
      - path: ./.env
        required: true
    environment:
      - DB_USER=postgres
      - DB_PASS='123'
      - DATABASE_URL=postgres://postgres:123@db:5432/pintrest_mock
      - REDIS_URL=redis://redis:6379
